### ISSUE TITLE
java.net.BindException: Address already in use: bind

### ISSUE THREAD

**Issue by cabfile** [DirtPowered/Release2Beta#8]
when trying this plugin on a Canyon (Minecraft Beta 1.7.3) server, it didn't work and threw an error
```
2021-09-21 19:10:10 [SEVERE] Error occurred while disabling ReleaseToBeta v1.2-SNAPSHOT (Is it up to date?): Cannot invoke "com.github.dirtpowered.releasetobeta.ReleaseToBeta.stop()" because "this.main" is null
java.lang.NullPointerException: Cannot invoke "com.github.dirtpowered.releasetobeta.ReleaseToBeta.stop()" because "this.main" is null
	at com.github.dirtpowered.releasetobeta.bootstrap.bukkit.BukkitBootstrap.onDisable(BukkitBootstrap.java:73)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:128)
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:906)
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:294)
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:287)
	at org.bukkit.plugin.SimplePluginManager.clearPlugins(SimplePluginManager.java:315)
	at org.bukkit.craftbukkit.CraftServer.reload(CraftServer.java:379)
	at org.bukkit.Bukkit.reload(Bukkit.java:173)
	at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:22)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:167)
	at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:350)
	at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:736)
	at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:701)
	at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:694)
	at net.minecraft.server.Packet3Chat.a(Packet3Chat.java:33)
	at net.minecraft.server.NetworkManager.b(NetworkManager.java:239)
	at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:89)
	at net.minecraft.server.NetworkListenThread.a(NetworkListenThread.java:71)
	at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:604)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:470)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:831)
```
those are all the plugins i currently have installed:
```
AuthMe.jar
ChatManager.jar
Cookbook.jar
iChat.jar
Modifyworld.jar
MultiVerse.jar
NoCheat.jar
over9000homes.jar
PathBuilder-1.0.jar
Permissions.jar
PermissionsEx.jar
ReleaseToBeta-1.2-SNAPSHOT.jar
WorldEdit.jar
```
what do i do?

**Comment by PF94** [comment]
oh fuck, i got this exact same issue and it's a dead end. welp.

**Comment by Dispnser** [comment]
change the ports in the config
